version: '3'
services:
  php:
    container_name: siler_examples_issue252_php
    image: php:7.4-fpm
    volumes:
      - ./:/var/www/html

  nginx:
    container_name: siler_examples_issue252_nginx
    image: nginx
    links:
      - php
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - 8000:80